version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - addressbook-db:/var/lib/postgresql/data


  addressbook:
    build:
      context: .
    environment:
      - DB_SCHEMA=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
    ports:
      - '3000:3000'
    depends_on:
      - postgres

volumes:
  addressbook-db: